// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/auth/github/index.ts";
import * as $1 from "./routes/api/auth/logout.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/dash/_middleware.ts";
import * as $4 from "./routes/dash/assets/index.tsx";
import * as $5 from "./routes/dash/index.tsx";
import * as $6 from "./routes/dash/profile/index.tsx";
import * as $7 from "./routes/dash/projects/[projectId].tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/sign-in.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/auth/github/index.ts": $0,
    "./routes/api/auth/logout.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/dash/_middleware.ts": $3,
    "./routes/dash/assets/index.tsx": $4,
    "./routes/dash/index.tsx": $5,
    "./routes/dash/profile/index.tsx": $6,
    "./routes/dash/projects/[projectId].tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/sign-in.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
